[project]
name = "mcp-adb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "mcp[cli]>=1.7.0",
    "uiautodev>=0.6.0",
    "uiautomator2>=3.2.9",
]
